### PR TITLE
Decoration properties integration.

### PR DESCRIPTION
**Pull request by dluechoy**
Integrates AI Changer w/ the properties panel so that show/hide of the Asset Properties Panel  will also remove it from view.

And as a first step torwards integrating this collection of mods.

| [Snow_Cat's questionable Asset Editor mods](http://steamcommunity.com/sharedfiles/filedetails/?id=455674755) |
| :-- |
|  |

| [Toggle Asset Properties Panel](https://steamcommunity.com/linkfilter/?url=http://steamcommunity.com/sharedfiles/filedetails/?id=451710073) |
| :-- |
|  |

### CODE REVIEW

**Comment by stkfd** [comment]
Thanks for the pull request, I'll have a quick look at it and then probably merge + update the steam workshop version in the next few days!

**Comment by dluechoy** [comment]
Thanks for the quick response.

I've also created a drop down list box version that requires further testing and refinement:  
https://github.com/dluechoy/BuildingAIChanger/tree/DropDown

As this relies on your code to do the useful parts, I would appreciate your feedback.

**Comment by stkfd** [comment]
Sorry it took me a while, had a busy week. I removed the text outline and added some padding to the input field, otherwise merged it unchanged. Will update the steam workshop version later today!

**Comment by stkfd** [comment]
I'll try your dropdown version tonight as well.

When I originally made the mod, I considered implementing something like that, but I realized that a classic dropdown select box (basically like the ones used for selecting the asset dimensions in the DecorationProperty Panel) would be inadequate for the number of available AI classes. You don't really want to open a dropdown that fills the whole screen from top to bottom.

So I would have had to make something a little more elaborate, maybe a popup window with a scrollable list in it. That's why I just decided to go the MVP route and simply make it a text input that requires you to know what you're doing but still verifies that the class exists.

Edit: Also, you seem to know your way around the code quite well and are more active than me at the moment. You could become a contributor here and in the steam workshop, if you'd like that.

**Pull request merged**
